# Map of all all_row keyword arguments to csv headers
HEADER_MAP = {
    'customer': 'Customer',
    'transaction_date': 'Transaction Date',
    'ref_number': 'RefNumber',
    'so_ref_number': 'SO RefNumber',
    'terms': 'Terms',
    'class': 'Class',
    'template_name': 'Template Name',
    'to_be_printed': 'To Be Printed',
    'ship_date': 'Ship Date',
    # TODO: yuck, would be nice to auto split lines in future
    'bill_to_line_1': 'BillTo Line1',
    'bill_to_line_2': 'BillTo Line2',
    'bill_to_line_3': 'BillTo Line3',
    'bill_to_line_4': 'BillTo Line4',
    'bill_to_city': 'BillTo City',
    'bill_to_state': 'BillTo State',
    'bill_to_postal': 'BillTo Postal',
    'bill_to_country': 'BillTo Country',
    'ship_to_line_1': 'ShipTo Line1',
    'ship_to_line_2': 'ShipTo Line2',
    'ship_to_line_3': 'ShipTo Line3',
    'ship_to_line_4': 'ShipTo Line4',
    'ship_to_city': 'ShipTo City',
    'ship_to_state': 'ShipTo State',
    'ship_to_postal': 'ShipTo Postal',
    'ship_to_country': 'ShipTo Country',
    'phone': 'Phone',
    'fax': 'Fax',
    'email': 'Email',
    'contact_name': 'Contact Name',
    'first_name': 'First Name',
    'last_name': 'Last Name',
    'rep': 'Rep',
    'due_date': 'Due Date',
    'ship_method': 'Ship Method',
    'customer_message': 'Customer Message',
    'memo': 'Memo',
    'item': 'Item',
    'quantity': 'Quantity',
    'description': 'Description',
    'price': 'Price',
    'is_pending': 'Is Pending',
    'item_line_class': 'Item Line Class',
    'service_date': 'Service Date',
    'fob': 'FOB',
    'customer_account_number': 'Customer Acct No',
    'sales_tax_item': 'Sales Tax Item',
    'to_be_emailed': 'To Be E-Mailed',
    'other': 'Other',
    'other1': 'Other1',
    'other2': 'Other2',
    'unit_of_measure': 'Unit of Measure',
    'ar_account': 'AR Account',
    'currency': 'Currency',
    'exchange_rate': 'Exchange Rate',
    'inventory_site': 'Inventory Site',
    'inventory_bin': 'Inventory Bin',
    'serial_lot_number': 'Serial /Lot Number',
    'sales_tax_code': 'Sales Tax Code',
}